server:
  port: 8080
spring:
  devtools:
    restart:
      enabled: true
  freemarker:
    cache: false
    settings:
      template_update_delay: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
