spring:
  datasource:
    url: jdbc:mysql://47.98.227.29:3306/novel?characterEncoding=utf-8
    username: wxd
    password: wxd
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*xml
  type-aliases-package: novel.dao.model
pagehelper:
  auto-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

oss:
  endpoint: oss-cn-hangzhou-internal.aliyuncs.com
  accessKeyId: LTAImpyGCxxxD2po
  accessKeySecret: TCNjZ8tm8nJ2J7CXBEJmTeJuZo5gFh
  bucketName: 61091b23-92d9-11e8-927a-00163e0f56a3
